/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myfirstproject;

import javax.swing.JFrame;

/**
 *
 * @author Meghana Patil
 */
public class Congrats extends javax.swing.JFrame {

   // private Object java;
   // private Object java;

    /**
     * Creates new form Congrats
     */
    public Congrats() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //gst_label.setText(PaymentProcess.gst_str+" Rs.");
        final_amt.setText(PaymentProcess.total_str+" Rs.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payment_confirm_panel = new javax.swing.JPanel();
        final_amt = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        anim_label1 = new javax.swing.JLabel();
        anim_label = new javax.swing.JLabel();
        anim_label2 = new javax.swing.JLabel();
        anim_label3 = new javax.swing.JLabel();
        anim_label4 = new javax.swing.JLabel();
        anim_label5 = new javax.swing.JLabel();
        anim_label6 = new javax.swing.JLabel();
        anim_label7 = new javax.swing.JLabel();
        anim_label8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        payment_confirm_panel.setBackground(new java.awt.Color(255, 255, 255));
        payment_confirm_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 20, true));
        payment_confirm_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        final_amt.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        payment_confirm_panel.add(final_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 210, 80));

        jPanel3.setBackground(new java.awt.Color(92, 188, 92));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Check Mark.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Congratulations!!");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 330, 79));

        payment_confirm_panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 480, 230));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Your Payment has Successfully received");
        payment_confirm_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 340, 41));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Paytm.png"))); // NOI18N
        payment_confirm_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 140, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bhim.png"))); // NOI18N
        payment_confirm_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 90, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Google Pay India.png"))); // NOI18N
        payment_confirm_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 80, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Phone Pe.png"))); // NOI18N
        payment_confirm_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 80, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MasterCard.png"))); // NOI18N
        payment_confirm_panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 80, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("OK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        payment_confirm_panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 130, 50));

        getContentPane().add(payment_confirm_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 540, 550));

        anim_label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Celebrate Green And Gold Sticker by Baylor University.gif"))); // NOI18N
        getContentPane().add(anim_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 260, 550));

        anim_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Celebrate Green And Gold Sticker by Baylor University.gif"))); // NOI18N
        getContentPane().add(anim_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 280, 550));

        anim_label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Celebrate Green And Gold Sticker by Baylor University.gif"))); // NOI18N
        getContentPane().add(anim_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 20, 310, 310));

        anim_label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Celebrate Green And Gold Sticker by Baylor University.gif"))); // NOI18N
        getContentPane().add(anim_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 0, 280, 550));

        anim_label4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Celebrate Green And Gold Sticker by Baylor University.gif"))); // NOI18N
        getContentPane().add(anim_label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 340, 280, 550));

        anim_label5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Celebrate Green And Gold Sticker by Baylor University.gif"))); // NOI18N
        getContentPane().add(anim_label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 730, 310, 310));

        anim_label6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Celebrate Green And Gold Sticker by Baylor University.gif"))); // NOI18N
        getContentPane().add(anim_label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 780, 320, 310));

        anim_label7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Celebrate Green And Gold Sticker by Baylor University.gif"))); // NOI18N
        getContentPane().add(anim_label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 740, 380, 310));

        anim_label8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Celebrate Green And Gold Sticker by Baylor University.gif"))); // NOI18N
        getContentPane().add(anim_label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 310, 310));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sticker by BookMyShow.gif"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 490, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_btn.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/film image.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Bookmyshowframe().show();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new PaymentProcess().show();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Congrats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Congrats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Congrats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Congrats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Congrats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anim_label;
    private javax.swing.JLabel anim_label1;
    private javax.swing.JLabel anim_label2;
    private javax.swing.JLabel anim_label3;
    private javax.swing.JLabel anim_label4;
    private javax.swing.JLabel anim_label5;
    private javax.swing.JLabel anim_label6;
    private javax.swing.JLabel anim_label7;
    private javax.swing.JLabel anim_label8;
    private javax.swing.JLabel final_amt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel payment_confirm_panel;
    // End of variables declaration//GEN-END:variables
}
